#!/usr/bin/env bash
# =-=            =-= #
# =-= DahBox mvn =-= #
# =-=            =-= #

# DAHBOX_VERSION=beta
# DAHBOX_HOME=/home/jlesage/Projets/Pristy/alfresco-collabora-online/.dahbox
# DAHBOX_DATE=lun. 03 juin 2024 21:28:31 CEST
# DAHBOX_COMMAND=dahbox create mvn --from maven --tag 3.9-eclipse-temurin-17  USER_HOME_DIR=\$HOME --command "mvn -Duser.home=\$HOME" --no-entrypoint
# DAHBOX_SHA=0218779abda782b9291ba8ce3bf8e67083c4a315


# 1. Check Image
image_id=$(podman image ls --filter 'label=fr.jeci.dahbox.name=mvn' --filter 'label=fr.jeci.dahbox.sha=0218779abda782b9291ba8ce3bf8e67083c4a315' --noheading --quiet)

# 2. Build Image
if [[ -z "$image_id" ]]; then
  echo "=-= DahBox Build mvn =-="
  container=$(buildah from docker.io/maven:3.9-eclipse-temurin-17)
  
  

  ## Include some buildtime annotations
  buildah config --label "fr.jeci.dahbox.name=mvn" "$container"
  buildah config --label "fr.jeci.dahbox.from=docker.io/maven:3.9-eclipse-temurin-17" "$container"
  buildah config --label "fr.jeci.dahbox.sha=0218779abda782b9291ba8ce3bf8e67083c4a315" "$container"
  buildah commit "$container" "dahbox/mvn:0218779abda782b9291ba8ce3bf8e67083c4a315"
  echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi

export PODMAN_USERNS=

# 3. Run container
podman run --rm \
  -e USER_HOME_DIR=$HOME \
  -v "$HOME:$HOME" -w "$PWD" \
  --init -it --net host --security-opt label=type:container_runtime_t --entrypoint "" \
  "dahbox/mvn:0218779abda782b9291ba8ce3bf8e67083c4a315" mvn -Duser.home=$HOME "$@"
